version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=test
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user@test.com
      PGADMIN_DEFAULT_PASSWORD: password123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: api
    environment:
      DATABASE_URL: postgresql://user:password123@postgres:5432/test
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/web/.env
    depends_on:
      - api

volumes:
  local_pgdata:
  pgadmin-data:
